# Pressfield · distribution-kit macOS lane config (see ~/Projects/distribution-kit)
DK_PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DK_PRODUCT_NAME="Pressfield"
DK_BUNDLE_ID="com.saagar.pressfield"
DK_VERSION="0.1.0"
DK_BUILD_CMD="pnpm tauri build"
DK_APP_PATH="$DK_PROJECT_DIR/src-tauri/target/release/bundle/macos/Pressfield.app"
DK_DMG_PATH="$DK_PROJECT_DIR/src-tauri/target/release/bundle/dmg/Pressfield_0.1.0_aarch64.dmg"
DK_SIGNING_IDENTITY="Developer ID Application: SAAGAR I PATEL (3TGZFKFNA4)"
DK_NOTARY_KEY_ID="6NPVH55ZWG"
DK_NOTARY_ISSUER_SERVICE="asc-radar"
DK_NOTARY_ISSUER_ACCOUNT="issuer_id"
DK_CHANNEL="github-release"
DK_GITHUB_REPO="saagpatel/Pressfield"
DK_TAG="v0.1.0"
DK_RELEASE_TITLE="Pressfield 0.1.0"
DK_RELEASE_NOTES_FILE="$DK_PROJECT_DIR/RELEASE-NOTES-0.1.0.md"
